import Header from "../../components/reusables/Header";
import { useEffect, useState } from "react"
import axios from "axios"
import '../../css/pages/Home.css'


const Home = () => {

    const [user, setUser] = useState({})


    useEffect(() => {
        if (localStorage.getItem("email")) {
            axios.get(`http://localhost:8080/getUserByEmail/${localStorage.getItem("email")}`)
                .then((response) => {
                    console.log(response.data)
                    setUser(response.data)
                })
                .catch((e) => {
                    console.log(e)
                })
        }
    }, [])



    return (
        <div className="flex-col container text">
            <Header headerText="PlannerFit" user={user} setUser={setUser} />
            <div className="flex-row full-width first-body">
                <div className="flex-col half-width">
                    <div className="first-body-text left ">
                        Build and Select workouts in minutes to use at the gym
                    </div>
                    <div className="first-body-under-text left ">
                        Select an autogenerated or self made workout to start your fitness jouney into self confidence
                    </div>
                </div>
                <div className="flex-col fourth-width first-body-image"></div>
                <div className="flex-col fourth-width second-body-image"></div>
            </div>
            <div className="flex-row full-width  second-body">
                <div className="third-width center">
                </div>
                <div className="third-width center-piece">
                    Customize your life with PlannetFit
                </div>
                <div className="third-width center">
                </div>
            </div>
            <div className="flex-row full-width  second-body">
                <div className="third-width center side-pieces">
                    Create your own custom workouts to bring to the gym
                </div>
                <div className="third-width or center">
                    OR
                </div>
                <div className="third-width center side-pieces">
                    Generate workouts through out program
                </div>
            </div>
        </div>
    )
}

export default Home